[package]
name = "touhou-sokoban"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.0"
specs = { version = "0.16.1", features = ["specs-derive"] }
strfmt = "0.1.6"
serde_json = "1.0.64"
